#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; TMP_WORK_DIR="$2"; REV="$3"
dokku_log_info2 "Testing docker monorepo presence..."
[[ ! -f "$TMP_WORK_DIR/.monorepo.dokku" ]] && exit

dokku_log_info2 "Docker monorepo detected"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  dockerfile="${line[1]}"
  dockerfile_path="$TMP_WORK_DIR/$dockerfile.Dockerfile"
  dockerignore_path="$dockerfile.dockerignore"

  [[ ! -f "$dockerfile_path" ]] &&\
   dokku_log_info2 "Cannot initiailize without Dockerfile named $dockerfile Dockerfile in monorepo root" && exit 1 

  [[ -f "$dockerignore_path" ]] && dokku_log_info2 "Using docker ignore from $dockerignore_path" && \
  cp -f "$dockerignore_path" "$TMP_WORK_DIR/.dockerignore"

  [[ ! -f "$TMP_WORK_DIR/.dockerignore" ]] && [[ ! -f "$dockerignore_path" ]] && dokku_log_warn \
  "No .dockerignore or $dockerignore_path found. your ENTIRE root directory will be used as docker context"

  dokku_log_info2 "Building Dockerfile from $dockerfile.Dockerfile"
  cp -f "$dockerfile_path" "$TMP_WORK_DIR/Dockerfile"
  exit

done 10<"$TMP_WORK_DIR/.monorepo.dokku"

dokku_log_info2 "The application $APP is not defined in .monorepo.dokku"
exit